sources:
  - name: predict
    handler:
      graphql:
        endpoint: ${PUBLIC_PREDICT_GRAPH_URL}
  - name: blocks
    handler:
      graphql:
        endpoint: ${PUBLIC_BLOCKS_GRAPH_URL}
  - name: chainlink
    handler:
      graphql:
        endpoint: ${PUBLIC_CHAINLINK_GRAPH_URL}
  - name: bets-memory
    handler:
      graphql:
        endpoint: ${PUBLIC_BETS_MEMORY_GRAPH_URL}

codegen:
  scalars:
    BigInt: bigint
    Bytes: string

documents:
  - ./src/schema.graphql