/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GamesPredictIndexImport } from './routes/games/predict/index'
import { Route as GamesPredictPairImport } from './routes/games/predict/$pair'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesPredictIndexRoute = GamesPredictIndexImport.update({
  id: '/games/predict/',
  path: '/games/predict/',
  getParentRoute: () => rootRoute,
} as any)

const GamesPredictPairRoute = GamesPredictPairImport.update({
  id: '/games/predict/$pair',
  path: '/games/predict/$pair',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/games/predict/$pair': {
      id: '/games/predict/$pair'
      path: '/games/predict/$pair'
      fullPath: '/games/predict/$pair'
      preLoaderRoute: typeof GamesPredictPairImport
      parentRoute: typeof rootRoute
    }
    '/games/predict/': {
      id: '/games/predict/'
      path: '/games/predict'
      fullPath: '/games/predict'
      preLoaderRoute: typeof GamesPredictIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/predict/$pair': typeof GamesPredictPairRoute
  '/games/predict': typeof GamesPredictIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/predict/$pair': typeof GamesPredictPairRoute
  '/games/predict': typeof GamesPredictIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/games/predict/$pair': typeof GamesPredictPairRoute
  '/games/predict/': typeof GamesPredictIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/predict/$pair' | '/games/predict'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/predict/$pair' | '/games/predict'
  id: '__root__' | '/' | '/games/predict/$pair' | '/games/predict/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesPredictPairRoute: typeof GamesPredictPairRoute
  GamesPredictIndexRoute: typeof GamesPredictIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesPredictPairRoute: GamesPredictPairRoute,
  GamesPredictIndexRoute: GamesPredictIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/games/predict/$pair",
        "/games/predict/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/games/predict/$pair": {
      "filePath": "games/predict/$pair.tsx"
    },
    "/games/predict/": {
      "filePath": "games/predict/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
