/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesPredictIndexRouteImport } from './routes/games/predict/index'
import { Route as GamesPredictPairRouteImport } from './routes/games/predict/$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPredictIndexRoute = GamesPredictIndexRouteImport.update({
  id: '/games/predict/',
  path: '/games/predict/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPredictPairRoute = GamesPredictPairRouteImport.update({
  id: '/games/predict/$pair',
  path: '/games/predict/$pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/predict/$pair': typeof GamesPredictPairRoute
  '/games/predict': typeof GamesPredictIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/predict/$pair': typeof GamesPredictPairRoute
  '/games/predict': typeof GamesPredictIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/predict/$pair': typeof GamesPredictPairRoute
  '/games/predict/': typeof GamesPredictIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/predict/$pair' | '/games/predict'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/predict/$pair' | '/games/predict'
  id: '__root__' | '/' | '/games/predict/$pair' | '/games/predict/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesPredictPairRoute: typeof GamesPredictPairRoute
  GamesPredictIndexRoute: typeof GamesPredictIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/predict/': {
      id: '/games/predict/'
      path: '/games/predict'
      fullPath: '/games/predict'
      preLoaderRoute: typeof GamesPredictIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/predict/$pair': {
      id: '/games/predict/$pair'
      path: '/games/predict/$pair'
      fullPath: '/games/predict/$pair'
      preLoaderRoute: typeof GamesPredictPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesPredictPairRoute: GamesPredictPairRoute,
  GamesPredictIndexRoute: GamesPredictIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
